### ISSUE TITLE
Think about generating database from xml pulled from the camera

### ISSUE THREAD

**Issue by coretl** [epics-containers/ioc-adaravis#16]
As we can do system commands in the iocsh:
```
epics> system "sleep 10"
```

We could do something like this:
```yaml
    databases:
      - file: $(ADARAVIS)/db/aravisCamera.template
        args:
          P:
          R:
          PORT:
          TIMEOUT:
          ADDR:

    pre_init:
      - value: |
          # aravisConfig(const char *portName, const char *cameraName, size_t maxMemory, int priority, int stackSize)
          aravisConfig("{{PORT}}", "{{ID}}", {{MEMORY}}, 0, 1)
          system "arv-tool -n <ip> genicam > genicam.xml"
          system "makeDb.py genicam,xml generated.template
          system "makePvi.py genicam,xml generated.pvi.device.yaml
          dbLoadRecords generated.template "P={{ P }},R={{ R }},PORT={{ PORT }}
```

Many questions, like should we pre-reference the database in the databases section, do we know where the pvi should be generated and how to get the right opi format from it, etc.
